[package]
name = "shell"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "2kbrowser"
path = "src/main.rs"

[dependencies]
css = { path = "../css" }
dom = { path = "../dom" }
layout = { path = "../layout" }
net = { path = "../net" }
paint = { path = "../paint" }
softbuffer = "0.4"
text = { path = "../text" }
winit = "0.30"

[lints]
workspace = true
