[package]
name = "paint"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
css = { path = "../css" }
layout = { path = "../layout" }
text = { path = "../text" }
tiny-skia = "0.11"

[dev-dependencies]
dom = { path = "../dom" }

[lints]
workspace = true
